### ISSUE TITLE
Задник при перенаправлении

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#14]
При перенаправлении по url wms.cr/t/ нужно добавить кнопку "Open in Telegram" с той же ссылкой и задник, как везде. Так работает https://t-do.ru/WMSCryptoBot - у них сначала отрабатывает перенаправление, а затем страница с кнопкой открывается

**Comment by vasinkd** [comment]
https://wms.cr/t/WMSCryptoBot
У меня ни на Ubuntu, ни на iOS не работает

**Comment by totaki** [comment]
http://beta.wms.cr/t/WMSCryptoBot

**Comment by totaki** [comment]
Сейчас только на beta

**Comment by vasinkd** [comment]
Все Ок, спасибо!
