### ISSUE TITLE
Итоговая информация по обмену

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#16]
- Обмен ERC20 
Пример: {'action': 'MT', 'data': {'coin': 60, 'account': 0, 'change': 0, 'address': 0, 'nonce': 18, 'gasPrice': 9000000000, 'gasLimit': 93915, 'to': '0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec', 'value': 0, 'data': '0xa9059cbb00000000000000000000000089d949c297940bf3193f97eb442cb432a06d917b0000000000000000000000000000000000000000000000127c738d0dc0798800', 'token_info': {'decimals': 18, 'symbol': 'POLY'}, 'exchange_info': {'value': 1764049, 'decimals': 8, 'symbol': 'BTC'}, 'lang': 'ru', 'anchor_hash': '1c951dd0086fdb6ff337f9eeda194e1188c94a0bdf0c6eef283687ef697ff1c0', 'anchor_password': 'fab4ae95d305b6d1f98e75bce09153df114ea6a993955fbde3217211649a5278', 'anchor_iv': '6c5168093542ca9fcafab256b0ba5af6'}}
*Что не так:*
а) Заголовок: "Обмен ETH > BTC", а должен быть "Обмен POLY > BTC" (в случае, если нет token_info["symbol"], можно "Покупка BTC")
б) Комиссия сети:  0.000845235 ETH, не хватает max. перед 0.000845235 ETH
в) Вы получите: NaN BTC, а должно быть ~0.01764049 BTC

- Отправка ERC20
У комиссии сети не хватает max. перед значением комиссии

**Comment by vasinkd** [comment]
- Обмен ETH
{'action': 'MT', 'data': {'coin': 60, 'account': 0, 'change': 0, 'address': 0, 'nonce': 18, 'gasPrice': 9000000000, 'gasLimit': 21000, 'to': '0x764c96ed8df6715631c3d6c909b2a8700caeaf24', 'value': 0.02506679200000003, 'data': '', 'exchange_info': {'value': 142646, 'decimals': 8, 'symbol': 'BTC'}, 'lang': 'ru', 'anchor_hash': '6de893d64923157fbed1ac6e3909b98dc54ace143be7c32bae1eea59226da471', 'anchor_password': 'c10c216079a173aa418084826e05d521bf8f93455abc7b0c96f64c25142e23a1', 'anchor_iv': '2b298cae763de5e08f310c135acd7c78'}}

**Не открылась страница**

**Comment by vasinkd** [comment]
- Обмен ETH
{'action': 'MT', 'data': {'coin': 0, 'useRBF': False, 'inputs': [{'change': 0, 'address': 20, 'account': 0, 'prevout_hash': '1264cb389fbd6368c3b9ed5f72bdc3821d5858eb3bff41a9d9243a0161700594', 'prevout_n': 1, 'value': 716220}], 'receiver': {'address': '3MBxQWvmRqfCdjBWw9FXLqXXM76bykT2ey', 'value': 711612}, 'locktime': 531490, 'exchange_info': {'value': 101236275000000016, 'decimals': 18, 'symbol': 'ETH'}, 'lang': 'ru', 'anchor_hash': '30c13803c72518cbbbe9b0a8ef0dbdb03e1cffde301cf0f21c71bc39b621b53f', 'anchor_password': '9ddf00bd662f8b11c91c6d0cbf4775971f28724bf764179e69a99c17f00ec234', 'anchor_iv': '65c9e6b310943ed6ec5ff185e98f4e23'}}
*Что не так*:
а) Получателя при обмене указывать не нужно 
б) Вы получите: NaN ETH, а должно быть  ~0.101236275000000014 ETH

**Comment by totaki** [comment]
Если конкретно эта задача не актуальна закрой
