### ISSUE TITLE
Обзор недоделок

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#17]
- Устаревшие/использованные ссылки отдают неправильное сообщение (https://github.com/WMSCrypto/WMSCrypto/issues/9)
- При проверке сложности пароля пробел считается запрещенным символом и отключает проверку сложности (https://github.com/WMSCrypto/WMSCrypto/issues/12)
- На последнем шаге при создании кошелька очень маленькие чек-боксы, в них сложно попасть пальцем, может сделать их больше или сделать так, чтобы они нажимались при нажатии на текст?
- Ethereum-обмен: "Вы получите: NaN BTC" (https://github.com/WMSCrypto/WMSCrypto/issues/16)
- erc20-обмен  (https://github.com/WMSCrypto/WMSCrypto/issues/16):
**Запрос:** {'action': 'MT', 'data': {'coin': 60, 'account': 0, 'change': 0, 'address': 0, 'nonce': 19, 'gasPrice': 141000000000, 'gasLimit': 93800, 'to': '0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec', 'value': 0, 'data': '0xa9059cbb0000000000000000000000007c86777104c0f985b090df30d835d873d955e4a200000000000000000000000000000000000000000000000ad78ebc5ac6200000', 'token_info': {'decimals': 18, 'symbol': 'POLY'}, 'exchange_info': {'value': 9254000000000000000, 'decimals': 18, 'symbol': 'OMG'}, 'lang': 'ru', 'anchor_hash': 'accc4eec2ff8aeb7680a5186072ea68fdee94f355be37230b2531a0fcba6429a', 'anchor_password': '93a98e8def6b7470bbf5a246315ce47965cdc1a6a6c34cd8d68d8767200d88e4', 'anchor_iv': '24d38600e506be61991b738374f00fd8'}}
**Результат:** https://imgur.com/uOp1piT

**Comment by totaki** [comment]
Ethereum-обмен: "Вы получите: NaN BTC"
![2018-07-17 09-43-49](https://user-images.githubusercontent.com/6254062/42800823-fd61ce04-89a5-11e8-9d0c-842e7b03ce0f.png)

erc20-обмен (#16)
![2018-07-17 09-37-34](https://user-images.githubusercontent.com/6254062/42800586-39545f22-89a5-11e8-9cc0-d1acf6ce2b62.png)
Я локально провели этот набор данных норм. Пиши ОСь и браузер который испольузуешь

**Comment by totaki** [comment]
По остальным готово.

**Comment by totaki** [comment]
Кажется это особенности округления float. Сделаю, свое через строку.

**Comment by totaki** [comment]
Давай пока не будем обращать внимания на нее и потестим функционал. У меня была мысль как это сделать и в целом нормальная, но я стал перебирать разные варианты и находить другие проблемы при работе с большими числами.

**Comment by vasinkd** [comment]
Все Ок, вынесу ошибки округления в отдельный issue
