### ISSUE TITLE
Вернуть проверку, что прикрепляется верный QR-ключ

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#21]
Раньше мы идентифицировали попытку прикрепить неправильный QR-ключ (сгенерированный с помощью неверного анкора). Проверяли это с помощью сокращенного хэша анкора. Теперь это перестало работать.

**Comment by totaki** [comment]
Кирилл сейчас вся логика работы с ключами заимплеменчина в одном месте `core/crypto` мне не хочется выносить ее части в другое место.

**Comment by vasinkd** [comment]
А что если при загрузке нового QR-ключа сделать что-то вроде имитации нажатия кнопки "Далее" при пустом поле для ввода пароля?

**Comment by totaki** [comment]
Проще сразу пытаться расшифровать. Наверное так и сделаю.

**Comment by vasinkd** [comment]
Работает :)
