### ISSUE TITLE
Ошибки округления

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#22]
При отображении значений пользователю зачастую нужно проводить операцию вида value / 10 ** CA.decimals
Как минимум в форме для eth-обмена было замечено, что некорректно отображаются комиссия сети и сумма к получению.

Сюда же второй вопрос: value в eth-транзакции приходит в post-запросе на получение формы в виде числа с плавающей запятой. Есть ли вероятность, что при считывании данного значения что-то пойдет не так? Сейчас перед отправкой я его обрабатываю как value / 10 ** 18, но для уверенности могу либо присылать в виде строки, где я уверен, что python не испортит float (а он так делает) либо в виде int, либо в виде строки, уже скорректированной на 10 ** decimals (однако, это подходит не для всех случаев)

**Comment by totaki** [comment]
https://www.w3schools.com/js/js_numbers.asp
https://learn.javascript.ru/number#%D0%BD%D0%B5%D1%82%D0%BE%D1%87%D0%BD%D1%8B%D0%B5-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F
Я посмотрел доки кажется мы не сможем поддерживать большую точность без ошибок в js

**Comment by vasinkd** [comment]
А почему не получится делать все операции в интах, а для деления использовать операции со строками?

Пример на Python:
```def num_to_str(num, decimals=0):
    assert isinstance(num, int), "not int in num_to_str: {}".format(num)
    assert num >= 0
    assert decimals >= 0
    
    str_num = str(num)
    len_num = len(str_num)
    diff = abs(decimals - len_num)
    before, after = "0", "0"

    if decimals >= len_num:
        after = diff * "0" + str_num
    else:
        before = str_num[:diff]
        after = str_num[diff:]
        
    return "{0}.{1}".format(before, after).rstrip("0").rstrip(".")```

**Comment by vasinkd** [comment]
Теперь строкой буду прислать:
1) В eth- и erc20-транзакции/обмене: gasPrice, gasLimit, value
2) В обменах: exchange_info["value"]

**Comment by vasinkd** [comment]
Ура!!! 🎆🎆🎆
Пошел смотреть)

**Comment by vasinkd** [comment]
Видимо из-за исправления этой ошибки что-то сломалось в алгоритме расшифровки транзакции. Возможно value "0" != 0

![screenshot from 2018-08-06 22-10-51](https://user-images.githubusercontent.com/24688061/43736301-cad6dabc-99c5-11e8-9f56-e7f793518825.png)

**Comment by vasinkd** [comment]
Возможно по той же причине в биткоин-транзакции неправильный заголовок:
![screenshot from 2018-08-06 22-36-00](https://user-images.githubusercontent.com/24688061/43737223-44e1d8d6-99c9-11e8-842b-c746497cc04e.png)
Должен быть Обмен BTC > OMG

Данные:
{'json': {'action': 'MT', 'data': {'coin': 0, 'useRBF': False, 'inputs': [{'change': 0, 'address': 22, 'account': 0, 'prevout_hash': 'd27ac2f9d03af1d9e29864c2622694ede1980ba40523e2a1ad03e7eb79b60bdb', 'prevout_n': 0, 'value': 673757}], 'receiver': {'address': '39o8E2s9qLFUX6W9csmEX2hyPdsHyG2DWX', 'value': 671837}, 'locktime': 535523, 'exchange_info': {'value': '8769000000000000000', 'decimals': 18, 'symbol': 'OMG'}, 'lang': 'ru', 'anchor_hash': '0ad5b071aa81a569ecbdc2ee48398cded8245de0b93c3605f492643e92b492c8', 'anchor_password': '48b694077777cdb37a5b6061a1e1daf5322ae818eb3a38acca0c7763fb0b7073', 'anchor_iv': '30de787410830c76ab71f238f5b6dc45'}}}
