### ISSUE TITLE
Обратная совместимость

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#23]
**Проблема:** Старые QR-ключи не работают на бете.

**Возможное решение:** В QR-ключи мы добавили версионный байт, думаю, можно использовать его, чтобы использовать ту версию кода, которая сможет корректно считать QR-ключ пользователя. Тогда при обнаружении старой версии QR-ключа мы сможем считать его, но при этом будем отображать предупреждение 'Ваш QR-ключ устарел. Для поддержания безопасности ваших криптоактивов на высоком уровне, рекомендуем обновить QR-ключ в разделе "Настройки".'

**Comment by vasinkd** [comment]
**Пример кошелька из старой версии:**
Мнемоник: "salad goddess album dose scatter split gesture crime blossom tonight hair normal cactus match affair until slush bunker teach onion recycle replace always silent"
QR-ключ:
![qrkey](https://user-images.githubusercontent.com/24688061/42970241-785064ba-8bb1-11e8-8e66-ed67f1fe8aef.png)
Пароль: "hello world"
Анкор (без шифрования, b64urlsafe): YJQrKql2yaIyDslRPyfnfbJlGRy8fEgy2rVjMaN7D4M=

**При попытке сменить пароль на бете (особенности смены системы передачи анкора учтены):**
![screenshot from 2018-07-20 00-15-40](https://user-images.githubusercontent.com/24688061/42970480-12014e4e-8bb2-11e8-9db9-beed6192e761.png)

**Comment by totaki** [comment]
Добавил на beta можно проверить

**Comment by vasinkd** [comment]
Все отлично, спасибо!

**Comment by vasinkd** [comment]
Возможно ли, что решение https://github.com/WMSCrypto/WMSCrypto/issues/21 сломало обратную совместимость? Прикрепляю анкор с основного сервера, вроде бы все делаю корректно, однако вижу следующее: 
![screenshot from 2018-08-06 23-03-42](https://user-images.githubusercontent.com/24688061/43738354-0125e002-99cd-11e8-9e73-15d0be6e9e62.png)

UPD: Перепроверил с новым кошельком на смене пароля. Точно сломано.

**Comment by vasinkd** [comment]
При подгрузке старого QR-ключа пропали карточки, осталась только заставка.

**Comment by vasinkd** [comment]
При подгрузке неправильного, но нового QR-ключа все отпработало правильно - выскочил ворнинг, что QR-ключ устарел/не соответствует аккаунту

**Comment by vasinkd** [comment]
Для иллюстрации создам новый кошелек на основном сервере:

Фраза для восстановления: welcome music same awful cause replace observe cart ride lazy milk code point spider friend increase tragic stay near fury mask wolf reopen trip

QR-ключ:
![new_main_wallet](https://user-images.githubusercontent.com/24688061/43833128-6aa74c14-9b12-11e8-8eb4-19307061468f.png)

Анкор в старой БД: "Hs5fLtJElaPtphIX1bAZzYQm08oAgS9o4UzxITSSjsk="

Создаем транзакцию на тестовом сервере:
{'json': {'action': 'MT', 'data': {'coin': 60, 'account': 0, 'change': 0, 'address': 0, 'nonce': 21, 'gasPrice': '60000000000', 'gasLimit': '134266', 'to': '0x1985365e9f78359a9b6ad760e32412f4a445e862', 'value': '0', 'data': '0xa9059cbb00000000000000000000000050333a327bad0ee064a17a78f47468c02d026bae000000000000000000000000000000000000000000000000204c52badedb1c00', 'token_info': {'decimals': 18, 'symbol': 'REP'}, 'exchange_info': {'value': '9649000000000000000', 'decimals': 18, 'symbol': 'EOS'}, 'lang': 'ru', 'anchor_hash': 'e7bd95385d0749411970993efbeed8af73531cec16ece86ad364b74105dd1138', 'anchor_password': '7e36bf0b33555a4d566158fbe6e25519dd32f448597c73a7f189dd4cfb5e2f83', 'anchor_iv': 'f7ee9f859950b3710722605bc5408a41'}}}

Ссылка:
http://beta.wms.cr/6a18fbc3-1dec-4d13-a789-ff3afba34357#ZJX2zERUj23FGI5GS42R2PgTqrWSkfCDLIZDTwZF6TWVXPNPtq96KR2K2+hn9KLA

Результат: падение сразу после прикрепления QR-ключа

**Comment by vasinkd** [comment]
На всякий случай добавлю еще раз код, который работает:

```
var CryptoJS = require("crypto-js");

encoded = 'ZJX2zERUj23FGI5GS42R2PgTqrWSkfCDLIZDTwZF6TWVXPNPtq96KR2K2+hn9KLA' // new_anchor из питона

var new_anchor = CryptoJS.enc.Base64.parse(encoded);

var key = CryptoJS.enc.Hex.parse("7e36bf0b33555a4d566158fbe6e25519dd32f448597c73a7f189dd4cfb5e2f83");
var iv = CryptoJS.enc.Hex.parse("f7ee9f859950b3710722605bc5408a41");

old_anchor = CryptoJS.AES.decrypt({ciphertext: new_anchor}, key, { iv: iv}).toString(CryptoJS.enc.Base64)
```

На выходе: "Hs5fLtJElaPtphIX1bAZzYQm08oAgS9o4UzxITSSjsk"

**Comment by totaki** [comment]
Кирилл я вернул все как было до проблем с проверкой хэш анкора в картинке. Проверь ее еще раз,  от тебя в случае ошибки мне нужны следующие данные:
- анкор как выклядел в строке запроса на старом сервер, один в один
- анкор как он выглядет в строке запроса на новом сервере при действиях с ним, если смена пароля то его тоже.
- пароль анкора, iv и хэш, если смена пароля то новый пароль тоже

**Comment by vasinkd** [comment]
Теперь получаю опять предыдущий вариант:

![screenshot from 2018-08-08 20-15-43](https://user-images.githubusercontent.com/24688061/43853141-df503c1c-9b47-11e8-9f65-664627a5c11a.png)

Данные те же, что указаны выше (QR-код, мнемоник)

Анкор на старом сервере: "Hs5fLtJElaPtphIX1bAZzYQm08oAgS9o4UzxITSSjsk=". В таком же виде я переношу его в БД на новом.

Транзакция, которая отдала результат, указанный на скрине выше:
Данные:
```
{'json': {'action': 'MT', 'data': {'coin': 60, 'account': 0, 'change': 0, 'address': 0, 'nonce': 21, 'gasPrice': '61000000000', 'gasLimit': '134266', 'to': '0x1985365e9f78359a9b6ad760e32412f4a445e862', 'value': '0', 'data': '0xa9059cbb00000000000000000000000050333a327bad0ee064a17a78f47468c02d026bae000000000000000000000000000000000000000000000000204c52badedb1c00', 'token_info': {'decimals': 18, 'symbol': 'REP'}, 'exchange_info': {'value': '4192199999999999488', 'decimals': 18, 'symbol': 'BNB'}, 'lang': 'ru', 'anchor_hash': 'ba6ea99edc96daec545bf16a8fce766052e78ad36d2fbf20891129b662114435', 'anchor_password': '2195577f0a7434a0f79e54ed7bed4b8f788aec7c0688a2dff50791809b4980cb', 'anchor_iv': 'ba1f4b77d83f3478e5cc0aee8867789d'}}}
```
Ссылка: http://beta.wms.cr/de25e4df-01c0-4f42-ba8c-46c09c75376b#+0LGwS2RwU0EHjN4mfM0VcHMXQLMZgW62aKLkaoSa3i7LwFzqIg3hkUAhRu4f2qK


Попробуем смену пароля:
{'json': {'action': 'CWP', 'data': {'lang': 'ru', 'anchor_hash': 'c09c32ff560cd2cd78b270312325af8f11fdaec7e6758e9705ae34a66a39fe64', 'anchor_password': 'f7aeaae350257f9dec10cd90de10bf3ae1b4294020bc768adbcc20bbfba0b32d', 'anchor_iv': 'e09ad0f43d03a22f2e65a604f00df929', 'new_anchor_hash': '93be53bcd080f1c9741c33dfd933cd616ebb8461d5b4a10bbf50e594471e378a'}}}

Ссылка: http://beta.wms.cr/2054999e-dcbf-462d-8638-63dde32eeb16#lF0BGL8vuRpiGtHuSEYrcxyvZSUEBqrpyWGykGyNS7iPSg0iw0S0kzAEwYzm2Hvo&DWTBSdg7bO6vXZHy8zDh5vT8kcVK8k3PRTgnqrP/4dE=

Результат: "QR-ключ либо устарел, либо не соответствует аккаунту"

**Comment by vasinkd** [comment]
Все  работает! В последний раз была ложная тревога.
