### ISSUE TITLE
Баг последнего шага

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#24]
**Описание:**
При отправке транзакции, если на шаге, на котором получена подписанная транзакция нажать "Назад", то вся форма падает

**Браузер**:  Firefox 61.0.1 (64-bit)
**ОС**: Ubuntu 16.04.

То же самое происходит и на iOS

**Comment by totaki** [comment]
Всмысле падает?

**Comment by totaki** [comment]
Создание транзакции вручную?

**Comment by vasinkd** [comment]
Остается только задник. Не вручную.

**Comment by totaki** [comment]
Ок
