### ISSUE TITLE
Офлайн режим, Resolver, версия и язык по умолчанию.

### ISSUE THREAD

**Issue by vasinkd** [WMSCrypto/WMSCrypto#27]
* При создании и прикреплении кошелька в офлайн режиме:
  * Пропали шаги 5 и 6: без них офлайн режим не имеет смысла. На шестом шаге вместо кнопки “Создать кошелек” должна быть кнопка “Скачать публичные ключи”, которая возвращает те же данные, которые мы отправляем на сервер в онлайн режиме в виде .json файла.
  * На 4 шаге должна быть внизу другая надпись (как и на 3 шаге при смене пароля), ведь офлайн режим нужен, чтобы ничего не хранить на устройствах с выходом в интернет:
    * *Данный QR-ключ должен храниться **только на устройстве без выхода в интернет**.* (RUS)
    * ***You should never store this QR Key on the devices with Internet access**.* (ENG)
* Кажется не работает wms.cr/t/WMSCryptoBot?start=hello. Пишет, что такого пользователя не существует. При этом на аналогичном сайте все работает: http://t-do.ru/WMSCryptoBot?start=hello (есть ощущение, что наш сайт сначала перенаправляет на https://wms.cr/t/WMSCryptoBot?start=hello?start=hello)
* Нужно поменять версию на 1.0, а в онлайн режиме убрать версию совсем – оставить WMSCrypto как было раньше, ведь на сайте всегда актуальная версия.
* Английский язык стоит сделать языком по умолчанию, если не передается никакая информация о языке.

**Comment by vasinkd** [comment]
Также в офлайн режиме при составлении транзакции на последнем шаге отображается подписанная транзакция. Нужно добавить кнопку "Скачать подписанную транзакцию", которая будет давать возможность скачать .json файл с подписанной транзакцией.

**Comment by totaki** [comment]
- [ ] При создании и прикреплении кошелька в офлайн режиме вернуть шаги 5 и 6. На шестом шаге вместо кнопки “Создать кошелек” должна быть кнопка “Скачать публичные ключи”, которая возвращает те же данные, которые мы отправляем на сервер в онлайн режиме в виде .json файла.
- [ ] При создании и прикреплении в офлайн режиме  на 4 шаге должна быть внизу другая надпись (как и на 3 шаге при смене пароля), ведь офлайн режим нужен, чтобы ничего не хранить на устройствах с выходом в интернет:
    * *Данный QR-ключ должен храниться **только на устройстве без выхода в интернет**.* (RUS)
    * ***You should never store this QR Key on the devices with Internet access**.* (ENG)

- [ ]  Кажется не работает wms.cr/t/WMSCryptoBot?start=hello. Пишет, что такого пользователя не существует. При этом на аналогичном сайте все работает: http://t-do.ru/WMSCryptoBot?start=hello (есть ощущение, что наш сайт сначала перенаправляет на https://wms.cr/t/WMSCryptoBot?start=hello?start=hello)
- [ ] Нужно поменять версию на 1.0, а в онлайн режиме убрать версию совсем – оставить WMSCrypto как было раньше, ведь на сайте всегда актуальная версия.
- [ ] Английский язык стоит сделать языком по умолчанию, если не передается никакая информация о языке.
- [ ] Также в офлайн режиме при составлении транзакции на последнем шаге отображается подписанная транзакция. Нужно добавить кнопку "Скачать подписанную транзакцию", которая будет давать возможность скачать .json файл с подписанной транзакцией.

**Comment by totaki** [comment]
Кирилл расскатил на beta, также прикладываю offline версию. Проверь если все ок расскатим релиз завтра.

[offline.html.zip](https://github.com/WMSCrypto/WMSCrypto/files/2363411/offline.html.zip)

**Comment by vasinkd** [comment]
Спасибо!
Поменяй еще, пожалуйста, в онлайн версии заголовок wmscrypto на WMSCrypto.
В остальном все отлично, можно публиковать новый релиз!

**Comment by totaki** [comment]
Хорошо, в течении дня расскачу
